"use client";

import { forwardRef, useEffect, useImperativeHandle, useRef } from "react";
import { COLS, ROWS } from "./engine/maze";
import {
  CLEARED,
  CUTSCENE,
  DYING,
  GAMEOVER,
  READY,
  createGame,
  endCutscene,
  setWanted,
  tick as stepGame,
  type GameState,
} from "./engine/game";
import {
  BONUS_SCORE_TICKS,
  CLEAR_FLASH_TICKS,
  CLEAR_HOLD_TICKS,
  CLEAR_TICKS,
  CUTSCENE_TICKS,
  DEATH_PAUSE_TICKS,
  DEATH_TICKS,
  bonusForLevel,
} from "./engine/levels";
import { DOWN, LEFT, RIGHT, TICK_HZ, UP, type Dir } from "./engine/types";
import {
  CONTRAST_GRAIN_FILL,
  CONTRAST_LIP_SCALE,
  CONTRAST_WALL_EDGE,
  CONTRAST_WALL_FILL,
  bakeGrains,
  bakeWalls,
  drawBonus,
  drawBonusScore,
  drawCutscene,
  drawPests,
  drawPitVideo,
  drawPlayer,
  drawPlayerDeath,
  drawPower,
  syncGrainLayer,
} from "./engine/render";
import { asset } from "@/lib/asset";
import {
  CUE_BONUS,
  CUE_CHOMP,
  CUE_DEATH,
  CUE_EXTRA_LIFE,
  CUE_GOLDEN,
  CUE_LEVEL_CLEAR,
  CUE_PEST,
  createCueWatch,
  observeCues,
  syncCueWatch,
} from "./engine/cues";
import {
  playChomp,
  playChompBonus,
  playChompDeath,
  playChompExtraLife,
  playChompGolden,
  playChompLevelClear,
  playChompPest,
  preloadChomp,
  resetChompVoice,
  toggleSound,
} from "@/lib/sound";

/**
 * Canvas host for RICE CHOMP. Owns the render loop, the canvas sizing and the keyboard,
 * and nothing else — the rules live in ./engine/game.ts and the painting in
 * ./engine/render.ts. Structured like src/components/grains/RiceBowlCanvas.tsx: a
 * forwardRef with an imperative handle, a rAF loop, DPR-aware sizing, ResizeObserver.
 *
 * THE ONE RULE THIS FILE ENFORCES: wall-clock time never reaches the simulation. It is
 * converted into a whole number of fixed ticks here and nowhere else, so the same
 * inputs always produce the same run regardless of frame rate. See engine/types.ts.
 */

const TICK_MS = 1000 / TICK_HZ;
/** Longest frame gap we will honour. Beyond this the backlog is dropped, not simulated. */
const MAX_FRAME_MS = 100;
/** Hard cap on catch-up ticks per frame, so a stall can never spiral. */
const MAX_TICKS_PER_FRAME = 10;
/** Cap the backing store. A 3× phone at full size is a lot of pixels for no gain. */
const MAX_DPR = 2;
/** How often the HUD is told what happened. 60fps setState would thrash React. */
const STATS_MS = 100;
/**
 * The maze-flash colours. Bright bone walls with a khaki keyline — the inverse of the
 * porcelain board, so the strobe reads as the maze lighting up rather than as a glitch.
 */
const FLASH_FILL = "#f4efe2";
const FLASH_EDGE = "#c4b370";
/**
 * THE TWO SELF-HOSTED ASSETS, and the only two the game has.
 *
 * Both go through asset(), so they carry the basePath and the immutable ?v=<BUILD_ID>
 * stamp like every other public file, and neither is a third-party request. Both were
 * re-encoded to sit inside the spec's budget — see docs/rice-chomp-plan.md.
 *
 * crossOrigin is deliberately NOT set on either. They are same-origin, and setting it
 * would opt into a CORS negotiation that can only ever fail; a video that fails CORS
 * taints the canvas, and a tainted canvas breaks every drawImage after it.
 */
const WALL_TEXTURE_SRC = "/chomp/paddy-wall.webp";
const PIT_VIDEO_SRC = "/chomp/rice.mp4";
/**
 * The theme's rounded display face, read off the document rather than hardcoded. The
 * family name is generated by next/font at build time, so the CSS variable is the only
 * place it is knowable — hardcoding "Fredoka" would silently fall through to a system
 * face the day the font pipeline changes.
 */
const LETTER_FONT_VAR = "--font-display-round";
/**
 * How far a thumb has to travel before it counts as a swipe, in CSS pixels. Low
 * enough that a flick of the thumb registers, high enough that the tap which
 * starts the game is not read as a turn. The origin RESETS after every turn, so a
 * player can trace a whole route with one continuous drag instead of lifting and
 * re-placing their thumb at each corner — which is what "playable one-thumbed"
 * actually means in a game where the corner is the skill.
 */
const SWIPE_PX = 22;

export interface ChompStats {
  score: number;
  lives: number;
  level: number;
  /** The level the run started on. Anything but 1 means this run cannot be submitted. */
  startLevel: number;
  grainsEaten: number;
  powerEaten: number;
  grainsRemaining: number;
  pestsEaten: number;
  tick: number;
  paused: boolean;
  /** One of the engine's Phase constants; the screen only distinguishes game over. */
  phase: number;
  /**
   * True while the attract screen is up. HOST-SIDE ONLY — the engine has no such
   * phase, no simulation runs, and the run that eventually starts is a brand new
   * state. See engine/cues.ts.
   */
  attract: boolean;
  /** Bumped on every fresh run, so the screen can file a score exactly once. */
  runId: number;
}

export interface ChompCanvasHandle {
  /** Throw the run away and start again. */
  reset: () => void;
  /** Leave the attract screen and begin a run. */
  start: () => void;
  /** Abandon the run and go back to the attract screen. */
  toAttract: () => void;
  /** Toggle pause; returns the new paused state. */
  togglePause: () => boolean;
  /** Queue a direction. The d-pad's only engine call, and the keyboard's too. */
  steer: (dir: Dir) => void;
}

/**
 * THE DEBUG ENTRY POINT. `/chomp?level=9` starts the run on level 9, so the tail of the
 * difficulty curve can be FELT rather than argued about — the crossover at level 7 is a
 * different game from level 1 and no amount of maths substitutes for playing it.
 *
 * It is deliberately the only debug affordance and deliberately visible: the run carries
 * startLevel, the HUD says DEBUG, and isScoreSubmittable() is false for the rest of the
 * run. Phase 7 gates the leaderboard on that, and server-side replay from level 1 rejects
 * such a trace anyway.
 *
 * Read from window.location rather than useSearchParams so the page stays statically
 * rendered — a useSearchParams() here would opt the whole route into client rendering.
 * Out-of-range or non-numeric values fall back to a normal, rankable run.
 */
const MAX_DEBUG_LEVEL = 99;

function bootLevel(): number {
  if (typeof window === "undefined") return 1;
  const raw = new URLSearchParams(window.location.search).get("level");
  const n = Number(raw);
  if (!raw || !Number.isInteger(n) || n < 1 || n > MAX_DEBUG_LEVEL) return 1;
  return n;
}

const KEY_TO_DIR: Record<string, Dir> = {
  ArrowUp: UP,
  ArrowDown: DOWN,
  ArrowLeft: LEFT,
  ArrowRight: RIGHT,
  w: UP,
  a: LEFT,
  s: DOWN,
  d: RIGHT,
  W: UP,
  A: LEFT,
  S: DOWN,
  D: RIGHT,
};

export const ChompCanvas = forwardRef<
  ChompCanvasHandle,
  {
    /** Polled roughly every 100ms with the run's headline numbers. */
    onStats?: (stats: ChompStats) => void;
    /**
     * Strips the golden-grain pulse, the bonus bob, the maze flash and the
     * interstitials. Presentation only — a reduced-motion run and a normal run are
     * tick-for-tick identical, which is the property the spec asks for.
     */
    reducedMotion?: boolean;
    /** Repaints the static layers in the high-contrast palette. See render.ts. */
    contrast?: boolean;
    className?: string;
  }
>(function ChompCanvas(
  { onStats, reducedMotion = false, contrast = false, className },
  ref,
) {
  const wrapRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const stateRef = useRef<GameState | null>(null);
  const pausedRef = useRef(false);
  const rafRef = useRef<number | null>(null);
  const lastRef = useRef(0);
  const accRef = useRef(0);

  // Baked layers + the size they were baked at.
  const wallsRef = useRef<HTMLCanvasElement | null>(null);
  const flashRef = useRef<HTMLCanvasElement | null>(null);
  const grainsRef = useRef<HTMLCanvasElement | null>(null);
  const bakedRef = useRef<Uint8Array | null>(null);
  const tileRef = useRef(0);
  const dprRef = useRef(1);
  /** The level the baked layers belong to. A new level refills the maze, so it re-bakes. */
  const bakedLevelRef = useRef(0);

  /**
   * The paddy wall texture, once it has decoded. Null until then, and null forever if it
   * fails — which is a non-event by design: bakeWalls with no texture is the flat
   * porcelain board the game shipped with, so a missing image costs decoration and
   * nothing else. First paint never waits on it.
   */
  const textureRef = useRef<HTMLImageElement | null>(null);
  /** Resolved once at boot from the theme vars; baked into the wall layer as lettering. */
  const fontRef = useRef<string | undefined>(undefined);
  /** The pit backdrop. Drawn per frame; see drawPitVideo() for why it is not baked. */
  const videoRef = useRef<HTMLVideoElement | null>(null);

  /** Milliseconds into the current interstitial. Host-side; never touches the run. */
  const cutsceneMsRef = useRef(0);

  /**
   * THE ATTRACT SCREEN IS A HOST FLAG, NOT A GAME PHASE. While it is set, tick() is
   * never called, so the attract screen provably costs the simulation nothing —
   * and starting a run builds a brand new state anyway, so nothing that happened
   * while it was up could reach the run even in principle.
   */
  const attractRef = useRef(true);
  const runIdRef = useRef(0);

  /** Previous-tick snapshot the audio cues are diffed against. Never written back. */
  const cueRef = useRef(createCueWatch());

  const statsAtRef = useRef(0);
  const onStatsRef = useRef(onStats);
  onStatsRef.current = onStats;
  const reducedRef = useRef(reducedMotion);
  reducedRef.current = reducedMotion;
  const contrastRef = useRef(contrast);

  /** Re-bake the static layers at the current tile size. */
  const bake = () => {
    const state = stateRef.current;
    const tilePx = tileRef.current;
    const dpr = dprRef.current;
    if (!state || tilePx <= 0) return;
    const hc = contrastRef.current;
    // HIGH CONTRAST TURNS THE TEXTURE OFF ENTIRELY, which is the whole bargain the spec
    // struck when it allowed a decorative background: black fill, bone keyline, no image
    // decoded and none drawn. The lettering stays — bone on black is the most legible it
    // ever is, and it is board furniture rather than decoration.
    wallsRef.current = bakeWalls(state.grid, tilePx, dpr, {
      fill: hc ? CONTRAST_WALL_FILL : undefined,
      edge: hc ? CONTRAST_WALL_EDGE : undefined,
      lipScale: hc ? CONTRAST_LIP_SCALE : undefined,
      texture: hc ? null : textureRef.current,
      fontFamily: fontRef.current,
    });
    // The flash layer stays flat on purpose: it is a strobe, and compositing a photograph
    // into a frame that is on screen for four ticks buys nothing. Its walls are bone, so
    // the lettering flips to a dark ink or it would vanish into them.
    flashRef.current = bakeWalls(state.grid, tilePx, dpr, {
      fill: FLASH_FILL,
      edge: FLASH_EDGE,
      fontFamily: fontRef.current,
      letterFill: "#14110d",
      letterHalo: "#f4efe2",
    });
    grainsRef.current = bakeGrains(
      state.grid,
      tilePx,
      dpr,
      hc ? CONTRAST_GRAIN_FILL : undefined,
    );
    bakedRef.current = Uint8Array.from(state.grid);
    bakedLevelRef.current = state.level;
  };

  const paint = () => {
    const canvas = canvasRef.current;
    const state = stateRef.current;
    const tilePx = tileRef.current;
    if (!canvas || !state || tilePx <= 0) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const dpr = dprRef.current;
    const w = COLS * tilePx;
    const h = ROWS * tilePx;

    // A new level puts every grain back, and the eaten-grain layer only ever ERASES.
    // Re-bake rather than trying to patch grains back into it.
    if (bakedLevelRef.current !== state.level) bake();

    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    ctx.fillStyle = "#000000";
    ctx.fillRect(0, 0, w, h);

    // The interstitial replaces the board entirely, and runs on the HOST's clock — the
    // simulation is frozen solid underneath it. See the CUTSCENE note in game.ts.
    if (state.phase === CUTSCENE) {
      drawCutscene(
        ctx,
        state.cutscene,
        Math.min(1, cutsceneMsRef.current / (CUTSCENE_TICKS * TICK_MS)),
        w,
        h,
        tilePx,
        !reducedRef.current,
      );
      return;
    }

    const walls = wallsRef.current;
    const grains = grainsRef.current;
    const baked = bakedRef.current;
    if (grains && baked) syncGrainLayer(grains, baked, state.grid, tilePx, dpr);

    // Blit at CSS scale: the layers already carry the device-pixel resolution.
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    if (walls) ctx.drawImage(walls, 0, 0);
    if (grains) ctx.drawImage(grains, 0, 0);
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);

    // The pit backdrop, under everything that moves. Drawn before the pests so the four
    // waiting in the pen composite OVER it — which is the z-order this wants, and which
    // comes free from being on the canvas rather than in a layer behind it. It is also
    // drawn before the phase branches below, so it is present on the attract screen and
    // through a death, exactly like the walls are.
    drawPitVideo(ctx, videoRef.current, tilePx);

    // Pulse is time-free: derived from the tick count, so it cannot desync.
    const pulse = reducedRef.current ? 1 : (Math.sin(state.tick / 9) + 1) / 2;
    drawPower(ctx, state.grid, tilePx, pulse);

    if (state.phase === DYING) {
      // The pests leave the board the moment the player is caught, so the last thing on
      // screen is the mistake rather than the crowd that punished it.
      const elapsed = DEATH_PAUSE_TICKS + DEATH_TICKS - state.phaseTicks;
      drawPlayerDeath(ctx, state.player, tilePx, (elapsed - DEATH_PAUSE_TICKS) / DEATH_TICKS);
      return;
    }

    if (state.phase === CLEARED) {
      // Cleared board: nobody on it, and the walls strobe. The strobe is a second BAKED
      // layer blitted on alternate beats rather than a per-frame tint, so the flash costs
      // one drawImage and not a recomposite of the whole maze.
      const into = CLEAR_TICKS - state.phaseTicks - CLEAR_HOLD_TICKS;
      const lit = !reducedRef.current && into >= 0 && Math.floor(into / CLEAR_FLASH_TICKS) % 2 === 0;
      if (lit && flashRef.current) {
        ctx.setTransform(1, 0, 0, 1, 0, 0);
        ctx.drawImage(flashRef.current, 0, 0);
        ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      }
      drawPlayer(ctx, state.player, tilePx, false);
      return;
    }

    const bonusKind = bonusForLevel(state.level).kind;
    // Bob is on the tick count, so it is the same on every machine and flat when the
    // player has asked for less motion.
    const bob = reducedRef.current ? 0.5 : (Math.sin(state.tick / 11) + 1) / 2;
    drawBonus(ctx, state.bonus, bonusKind, tilePx, bob);
    drawPests(ctx, state.pests, tilePx, state.frightTicks, !reducedRef.current);
    drawPlayer(ctx, state.player, tilePx, !state.player.blocked && state.phase !== READY);
    drawBonusScore(ctx, state.bonus, tilePx, BONUS_SCORE_TICKS);
  };

  const publishStats = (now: number, force = false) => {
    const state = stateRef.current;
    if (!state) return;
    if (!force && now - statsAtRef.current < STATS_MS) return;
    statsAtRef.current = now;
    onStatsRef.current?.({
      score: state.score,
      lives: state.lives,
      level: state.level,
      startLevel: state.startLevel,
      grainsEaten: state.grainsEaten,
      powerEaten: state.powerEaten,
      grainsRemaining: state.grainsRemaining,
      pestsEaten: state.pestsEaten,
      tick: state.tick,
      paused: pausedRef.current,
      phase: state.phase,
      attract: attractRef.current,
      runId: runIdRef.current,
    });
  };

  /**
   * Turn what the last tick did into sound.
   *
   * Called immediately after tick(), inside the fixed-timestep loop. It reads the
   * state and writes nothing to it — observeCues() takes a readonly view and
   * allocates nothing — and every play call is fire-and-forget, so a browser with
   * no AudioContext, a blocked decode or a muted player all cost exactly the same
   * as a player with sound on: nothing. Audio can therefore neither stall the
   * simulation nor change it. See engine/cues.ts for why sound is derived here
   * rather than pushed from the engine.
   */
  const soundFor = (state: GameState) => {
    const cues = observeCues(cueRef.current, state);
    if (cues === 0) return;
    if (cues & CUE_CHOMP) playChomp();
    if (cues & CUE_GOLDEN) playChompGolden();
    if (cues & CUE_PEST) playChompPest(cueRef.current.chain);
    if (cues & CUE_BONUS) playChompBonus();
    if (cues & CUE_EXTRA_LIFE) playChompExtraLife();
    if (cues & CUE_LEVEL_CLEAR) playChompLevelClear();
    if (cues & CUE_DEATH) playChompDeath();
  };

  const ensureRunning = () => {
    if (rafRef.current != null) return;
    lastRef.current = performance.now();
    const frame = (t: number) => {
      const state = stateRef.current;
      if (!state) {
        rafRef.current = null;
        return;
      }

      const raw = t - lastRef.current;
      lastRef.current = t;

      // Attract. The board is painted as a still life behind the overlay and the
      // simulation is not touched at all — not one tick, not the RNG, nothing.
      if (attractRef.current) {
        accRef.current = 0;
        paint();
        publishStats(t);
        rafRef.current = requestAnimationFrame(frame);
        return;
      }

      if (state.phase === CUTSCENE) {
        // The simulation does not advance at all here. The cutscene has its own clock,
        // and when it runs out — or the player skips, or reduced motion skips it before
        // the first frame — the run picks up exactly where it stopped.
        if (reducedRef.current) {
          endCutscene(state);
        } else {
          cutsceneMsRef.current += Math.min(Math.max(raw, 0), MAX_FRAME_MS);
          if (cutsceneMsRef.current >= CUTSCENE_TICKS * TICK_MS) endCutscene(state);
        }
        accRef.current = 0;
        paint();
        publishStats(t);
        rafRef.current = requestAnimationFrame(frame);
        return;
      }
      cutsceneMsRef.current = 0;

      if (!pausedRef.current) {
        // Clamp before accumulating: a backgrounded tab or a long GC pause must not
        // become hundreds of simulated ticks the moment we come back.
        accRef.current += Math.min(Math.max(raw, 0), MAX_FRAME_MS);
        let n = 0;
        while (accRef.current >= TICK_MS && n < MAX_TICKS_PER_FRAME) {
          stepGame(state);
          soundFor(state);
          accRef.current -= TICK_MS;
          n++;
        }
        if (n >= MAX_TICKS_PER_FRAME) accRef.current = 0; // drop the backlog
      }

      paint();
      publishStats(t);
      rafRef.current = requestAnimationFrame(frame);
    };
    rafRef.current = requestAnimationFrame(frame);
  };

  /**
   * Throw the run away and start again. Touches only refs, so the copy captured by the
   * keyboard effect on first render stays correct for the life of the component.
   */
  const restart = () => {
    const state = createGame(bootLevel());
    stateRef.current = state;
    accRef.current = 0;
    cutsceneMsRef.current = 0;
    pausedRef.current = false;
    attractRef.current = false;
    runIdRef.current++;
    // Point the cue watcher at the new run before a tick happens, so the first
    // observation is a diff and not a burst of cues for a game coming into being.
    syncCueWatch(cueRef.current, state);
    resetChompVoice();
    bake();
    paint();
    publishStats(performance.now(), true);
  };

  /** Back to the attract screen, with a fresh board painted behind it. */
  const toAttract = () => {
    const state = createGame(bootLevel());
    stateRef.current = state;
    accRef.current = 0;
    cutsceneMsRef.current = 0;
    pausedRef.current = false;
    attractRef.current = true;
    syncCueWatch(cueRef.current, state);
    bake();
    paint();
    publishStats(performance.now(), true);
  };

  useImperativeHandle(ref, () => ({
    reset: restart,
    start: restart,
    toAttract,
    togglePause: () => {
      // Pause is meaningless on the attract screen and on a finished run, and a
      // pause overlay that can be raised over "Game over" is a dead end.
      const state = stateRef.current;
      if (attractRef.current || !state || state.phase === GAMEOVER) return false;
      pausedRef.current = !pausedRef.current;
      publishStats(performance.now(), true);
      return pausedRef.current;
    },
    steer: (dir: Dir) => {
      const state = stateRef.current;
      if (!state) return;
      if (attractRef.current) {
        restart();
        return;
      }
      // On-screen controls skip an interstitial too, for the same reason the keyboard
      // does: a tap should mean "get on with it", not nothing.
      if (state.phase === CUTSCENE) {
        endCutscene(state);
        return;
      }
      setWanted(state, dir);
    },
  }));

  // --- boot -----------------------------------------------------------------
  useEffect(() => {
    const wrap = wrapRef.current;
    const canvas = canvasRef.current;
    if (!wrap || !canvas) return;

    const booted = createGame(bootLevel());
    stateRef.current = booted;
    syncCueWatch(cueRef.current, booted);

    // The lettering's face, from the theme block in globals.css. Read once — it cannot
    // change for the life of the page — and passed into every bake from here on.
    fontRef.current =
      getComputedStyle(document.documentElement).getPropertyValue(LETTER_FONT_VAR).trim() ||
      undefined;

    /** Set by the cleanup, so a late decode or font load cannot bake into a dead canvas. */
    let disposed = false;

    /**
     * Re-bake once the webfont has actually arrived.
     *
     * The lettering is baked ONCE, and `ctx.measureText` does not wait for anything: if
     * Fredoka has not loaded at the moment bakeWalls runs, canvas quietly measures and
     * draws the fallback face, and — because it is baked — it stays wrong for the life of
     * the page. There is no visible error and nothing in the console; it just is not the
     * right typeface, forever. `document.fonts.ready` is the only signal that rules this
     * out, and one extra bake at boot is a cheap price for it.
     *
     * This is not covered by the texture's re-bake: the high-contrast board never loads a
     * texture, so on that path this is the only thing that would fix the face.
     */
    void document.fonts?.ready?.then(() => {
      if (disposed) return;
      bake();
      paint();
    });

    /**
     * Decode the wall texture OFF the critical path. The board renders on its solid fill
     * from the very first frame; when (and only if) the image decodes, the static layers
     * are re-baked once and the texture appears. A failure never reaches the player.
     */
    const img = new Image();
    img.decoding = "async";
    img.src = asset(WALL_TEXTURE_SRC);
    img
      .decode()
      .then(() => {
        if (disposed) return;
        textureRef.current = img;
        bake();
        paint();
      })
      .catch((err: unknown) => {
        // NOT silent. A caught failure here produces a board that looks completely
        // healthy — the flat porcelain maze, no error, nothing in the network tab that
        // looks wrong — which is indistinguishable from the texture being applied and
        // having no effect. That ambiguity cost a round trip once; it does not get to
        // cost another. The board still degrades gracefully; it just says so.
        console.warn("[chomp] wall texture failed to decode; board stays flat", err);
      });
    // Decode the eight clips now rather than on the first grain. A suspended
    // AudioContext decodes fine, and the first chomp lands within a second of the
    // player's first input with no second chance if it is not ready.
    preloadChomp();

    /**
     * Letterbox: pick the largest whole-pixel tile that fits both axes, then size the
     * canvas to exactly COLS×ROWS tiles. The wrapper centres it, so the maze keeps its
     * 28:31 aspect at any viewport without CSS scaling blurring the render.
     */
    let retry = 0;
    const resize = () => {
      const box = wrap.getBoundingClientRect();

      // A degenerate box means layout has not settled yet (or an ancestor has no
      // definite height). Retry on the next frame rather than committing to a size —
      // committing here is what produced the 4px-tile bug: the canvas was sized from a
      // bad measurement, the content-sized wrapper then shrank to the canvas, and the
      // next measurement agreed with itself forever.
      if (box.width < COLS || box.height < ROWS) {
        if (retry < 60) {
          retry++;
          requestAnimationFrame(resize);
        }
        return;
      }
      retry = 0;

      const tilePx = Math.floor(Math.min(box.width / COLS, box.height / ROWS));
      const dpr = Math.min(window.devicePixelRatio || 1, MAX_DPR);
      if (tilePx === tileRef.current && dpr === dprRef.current) return;

      tileRef.current = tilePx;
      dprRef.current = dpr;
      const w = COLS * tilePx;
      const h = ROWS * tilePx;
      canvas.style.width = `${w}px`;
      canvas.style.height = `${h}px`;
      canvas.width = Math.round(w * dpr);
      canvas.height = Math.round(h * dpr);
      bake();
      paint();
    };
    resize();

    // Observe the WRAPPER, not the canvas: this handler resizes the canvas, and
    // observing the thing you resize is how you get a feedback loop.
    const ro = new ResizeObserver(resize);
    ro.observe(wrap);

    ensureRunning();

    return () => {
      disposed = true;
      ro.disconnect();
      if (rafRef.current != null) cancelAnimationFrame(rafRef.current);
      rafRef.current = null;
      stateRef.current = null;
      wallsRef.current = null;
      grainsRef.current = null;
      flashRef.current = null;
      bakedRef.current = null;
      textureRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // --- keyboard -------------------------------------------------------------
  useEffect(() => {
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.metaKey || e.ctrlKey || e.altKey) return;
      const target = e.target as HTMLElement | null;
      if (target && /^(INPUT|TEXTAREA|SELECT)$/.test(target.tagName)) return;
      nudgeVideo();

      // Is the focused thing a control that owns Space/Enter itself? Widened from
      // `tagName === "BUTTON"` in Phase 5.6, when the site nav — a bar of LINKS —
      // was mounted above the board. A window handler that preventDefaults Enter
      // cancels an anchor's activation, so the narrow check quietly made every link
      // on the page keyboard-dead, including the "back to the paddy" one that was
      // already here. Arrow keys and WASD are deliberately NOT covered by this: a
      // link with focus must never stop the player steering.
      const onControl = !!target?.closest("a[href],button,[role='button']");

      // M mutes, and it drives the SITE's sound switch rather than a private one —
      // there is one sound toggle on this site and this is it. See prefs.ts.
      if (e.key === "m" || e.key === "M") {
        e.preventDefault();
        toggleSound();
        return;
      }

      // Attract: press anything to play. Tab and the bare modifiers are excluded so
      // that a keyboard player can still reach the Start button and the settings
      // rather than having the game begin under them the moment they navigate.
      if (attractRef.current) {
        if (e.key === "Tab" || e.key === "Shift" || e.key === "Control" || e.key === "Alt") return;
        // Space and Enter on a focused control are the browser's own click; let it
        // through or the run starts twice — and on a link, it starts instead of
        // navigating, which is worse.
        if (onControl && (e.key === " " || e.key === "Enter")) return;
        e.preventDefault();
        restart();
        return;
      }

      // Cutscenes are skippable, and by ANY key rather than a documented one — a player
      // who wants the interstitial gone should not have to find out which button does it.
      const showing = stateRef.current;
      if (showing && showing.phase === CUTSCENE) {
        e.preventDefault();
        endCutscene(showing);
        return;
      }

      const dir = KEY_TO_DIR[e.key];
      if (dir !== undefined) {
        // Arrows scroll the page and WASD can trigger browser quick-find; either would
        // fight every input. Space is handled below for the same reason.
        e.preventDefault();
        const state = stateRef.current;
        if (state) setWanted(state, dir);
        return;
      }

      // Space and Enter restart from game over. GAMEOVER runs no simulation, so without
      // this the board is inert and every key is dead — a dead end, not a screen.
      //
      // Skipped when a control has focus: the overlay's own "Play again" is focused on
      // game over, and the browser already turns Space and Enter into a click on it.
      // Handling both here as well would restart twice — and on a nav link it would
      // cancel the navigation outright.
      if (e.key === " " || e.key === "Enter") {
        const state = stateRef.current;
        // preventDefault regardless of phase: space scrolls the page, and the page
        // scrolling under a fixed-size board is the bug this stops.
        if (!onControl) e.preventDefault();
        if (!onControl && state && state.phase === GAMEOVER) restart();
        return;
      }

      if (e.key === "p" || e.key === "P" || e.key === "Escape") {
        e.preventDefault();
        const s = stateRef.current;
        if (!s || s.phase === GAMEOVER) return;
        pausedRef.current = !pausedRef.current;
        publishStats(performance.now(), true);
      }
    };
    // Not passive: we preventDefault on the arrow keys.
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
    // `restart` is deliberately omitted: it touches only refs, so the copy captured on the
    // first render stays correct, and listing it would rebind this listener every render.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // --- the pit backdrop -----------------------------------------------------
  /**
   * Ask the video to play, and shrug if the browser says no.
   *
   * Autoplay is a permission, not a guarantee. `muted` + `playsInline` is what earns it on
   * mobile and is why both are set — but a browser may still refuse, and a rejected
   * play() that is not caught is an unhandled rejection in the console of every visitor.
   * When it is refused the element simply sits on its first frame, which drawPitVideo
   * paints as a still, and the next user gesture tries again.
   */
  const nudgeVideo = () => {
    const v = videoRef.current;
    if (!v || reducedRef.current || !v.paused) return;
    void v.play().catch(() => {
      /* Still refused. The pit shows a still frame; nothing else changes. */
    });
  };

  useEffect(() => {
    const v = videoRef.current;
    if (!v) return;
    if (reducedMotion) {
      // Reduced motion gets the still, not a hidden animation: pause and rewind, and
      // drawPitVideo keeps painting whatever frame is parked there.
      v.pause();
      try {
        v.currentTime = 0;
      } catch {
        /* Seeking before metadata arrives throws in some browsers; harmless. */
      }
      return;
    }
    void v.play().catch(() => {
      /* See nudgeVideo. */
    });
  }, [reducedMotion]);

  // --- contrast ------------------------------------------------------------
  // The static layers carry the palette, so a change of preference is a re-bake and
  // nothing else. Skipped on the first run, where boot has already baked.
  const contrastBakedRef = useRef(contrast);
  useEffect(() => {
    contrastRef.current = contrast;
    if (contrastBakedRef.current === contrast) return;
    contrastBakedRef.current = contrast;
    bake();
    paint();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [contrast]);

  // --- pause when the page is not visible -----------------------------------
  useEffect(() => {
    const onHide = () => {
      if (document.visibilityState === "hidden") {
        pausedRef.current = true;
        publishStats(performance.now(), true);
      }
    };
    document.addEventListener("visibilitychange", onHide);
    return () => document.removeEventListener("visibilitychange", onHide);
  }, []);

  // --- swipe ----------------------------------------------------------------
  /**
   * A drag anywhere over the board steers. The origin is reset every time a turn
   * fires, so one continuous thumb drag can trace a whole route — down, right, up —
   * without ever lifting off. Lifting without having travelled far enough is a TAP,
   * which means "get on with it": start the run, skip the interstitial, play again.
   *
   * Both routes end at steer(), which is setWanted() — the same and only engine call
   * the keyboard makes. Touch adds no way to affect the run that the keyboard did not
   * already have, which is why it cannot change a trace.
   */
  const swipeRef = useRef({ active: false, x: 0, y: 0, turned: false });

  const onPointerDown = (e: React.PointerEvent<HTMLDivElement>) => {
    // The same gesture that unlocks the AudioContext also unblocks the pit video, for
    // the same reason: both are things the browser will not start on its own.
    nudgeVideo();
    swipeRef.current = { active: true, x: e.clientX, y: e.clientY, turned: false };
    e.currentTarget.setPointerCapture?.(e.pointerId);
  };

  const onPointerMove = (e: React.PointerEvent<HTMLDivElement>) => {
    const s = swipeRef.current;
    if (!s.active) return;
    const dx = e.clientX - s.x;
    const dy = e.clientY - s.y;
    if (Math.abs(dx) < SWIPE_PX && Math.abs(dy) < SWIPE_PX) return;
    const dir =
      Math.abs(dx) > Math.abs(dy) ? (dx > 0 ? RIGHT : LEFT) : dy > 0 ? DOWN : UP;
    s.x = e.clientX;
    s.y = e.clientY;
    s.turned = true;
    const state = stateRef.current;
    if (attractRef.current) {
      restart();
      return;
    }
    if (state && state.phase === CUTSCENE) {
      endCutscene(state);
      return;
    }
    if (state) setWanted(state, dir);
  };

  const onPointerUp = (e: React.PointerEvent<HTMLDivElement>) => {
    const s = swipeRef.current;
    s.active = false;
    e.currentTarget.releasePointerCapture?.(e.pointerId);
    if (s.turned) return;
    const state = stateRef.current;
    if (attractRef.current) {
      restart();
      return;
    }
    if (!state) return;
    if (state.phase === CUTSCENE) {
      endCutscene(state);
      return;
    }
    if (state.phase === GAMEOVER) restart();
  };

  return (
    // The canvas is taken OUT of flow and centred absolutely so it can never
    // contribute to the size of the box being measured. Measuring an ancestor of the
    // thing you resize is a feedback loop waiting to happen; this makes it structurally
    // impossible rather than merely unlikely.
    //
    // The swipe handlers sit on the WRAPPER rather than the canvas, so the letterbox
    // bars are live too — on a portrait phone that is a meaningful strip of thumb room
    // above and below the maze, and a swipe that dies because it started two pixels
    // off the board is the kind of thing that makes touch controls feel broken.
    <div
      ref={wrapRef}
      className={className}
      style={{ position: "relative", touchAction: "none" }}
      onPointerDown={onPointerDown}
      onPointerMove={onPointerMove}
      onPointerUp={onPointerUp}
      onPointerCancel={onPointerUp}
    >
      {/*
        THE PIT BACKDROP'S SOURCE, and nothing more. It is never seen: every pixel the
        player sees is drawn from it onto the canvas by drawPitVideo, which is what keeps
        it aligned through resize, DPR changes and the portrait letterbox for free.

        It is 1×1 and transparent rather than display:none, because a display:none video
        is not guaranteed to decode — and a video that does not decode looks exactly like
        one that is merely slow. muted + playsInline are load-bearing: without both,
        mobile browsers refuse to autoplay at all.
      */}
      <video
        ref={videoRef}
        src={asset(PIT_VIDEO_SRC)}
        muted
        loop
        playsInline
        autoPlay
        preload="auto"
        aria-hidden="true"
        tabIndex={-1}
        style={{
          position: "absolute",
          width: 1,
          height: 1,
          opacity: 0,
          pointerEvents: "none",
          left: 0,
          top: 0,
        }}
      />
      <canvas
        ref={canvasRef}
        role="img"
        aria-label="RICE CHOMP maze. Steer the grain of rice with the arrow keys, or swipe, to clear every grain."
        style={{
          display: "block",
          position: "absolute",
          left: "50%",
          top: "50%",
          transform: "translate(-50%, -50%)",
          touchAction: "none",
        }}
      />
    </div>
  );
});
