"use client";

/**
 * GRAINSNAKE — the optional loop, generated by oscillators rather than shipped.
 *
 * ── WHY THERE IS NO MUSIC FILE ──────────────────────────────────────────────────
 * The brief was "no file over a few KB", and a loop is the one asset that cannot
 * meet it: two seconds of mono 16-bit at 22.05 kHz is ~88 KB before it has said
 * anything, and a loop short enough to be small is a loop short enough to be
 * maddening. So it is synthesized live — **zero bytes, no request, and it cannot go
 * missing at runtime**, which is the same argument the spec makes for drawing
 * everything else procedurally.
 *
 * It is deliberately almost nothing: a slow pentatonic pattern on a soft triangle
 * voice, well under the effects. Music you notice while trying to hold 15 cells a
 * second is music you turn off.
 *
 * ── IT USES THE SHARED CONTEXT ──────────────────────────────────────────────────
 * A page must have exactly one AudioContext — iOS caps how many a document may
 * create and only unlocks the ones touched inside a gesture, so a second one is a
 * second thing that can be silently suspended forever with no symptom but silence.
 * `getAudioContext()` hands back the one `src/lib/sound.ts` already owns.
 *
 * NOTHING HERE TOUCHES THE SIMULATION. It has its own clock — the AudioContext's —
 * which is exactly why it may: nothing it schedules is ever read by a rule.
 */

import { getAudioContext } from "@/lib/sound";

/** A minor pentatonic, low and unhurried. Hz. */
const NOTES = [174.61, 196.0, 233.08, 261.63, 293.66, 349.23];
/** Seconds between notes. Slow enough to sit under the game rather than in it. */
const STEP_SEC = 0.42;
/** How far ahead to schedule. Long enough to survive a stalled frame, short enough
 *  that stopping is immediate. */
const LOOKAHEAD_SEC = 0.6;
const TICK_MS = 200;
/** Master level. Low on purpose — this is a bed, not a track. */
const GAIN = 0.055;

let master: GainNode | null = null;
let timer: ReturnType<typeof setInterval> | null = null;
let nextAt = 0;
let step = 0;
/** A tiny deterministic sequence, so the loop is the same every session. */
const PATTERN = [0, 2, 4, 2, 1, 3, 5, 3, 0, 4, 2, 5];

function scheduleNote(ctx: AudioContext, at: number, hz: number): void {
  const osc = ctx.createOscillator();
  const gain = ctx.createGain();
  osc.type = "triangle";
  osc.frequency.value = hz;
  // A soft attack and a long decay: a plucked edge here would compete with the eat
  // blip, which is the one sound that must always cut through.
  gain.gain.setValueAtTime(0.0001, at);
  gain.gain.exponentialRampToValueAtTime(1, at + 0.08);
  gain.gain.exponentialRampToValueAtTime(0.0001, at + STEP_SEC * 1.8);
  osc.connect(gain).connect(master ?? ctx.destination);
  osc.start(at);
  osc.stop(at + STEP_SEC * 2);
}

function pump(): void {
  const ctx = getAudioContext();
  if (!ctx || !master) return;
  while (nextAt < ctx.currentTime + LOOKAHEAD_SEC) {
    scheduleNote(ctx, nextAt, NOTES[PATTERN[step % PATTERN.length]]);
    step++;
    nextAt += STEP_SEC;
  }
}

export function startMusic(): void {
  const ctx = getAudioContext();
  if (!ctx || timer !== null) return;
  if (ctx.state === "suspended") void ctx.resume().catch(() => {});
  master = ctx.createGain();
  master.gain.value = GAIN;
  master.connect(ctx.destination);
  nextAt = ctx.currentTime + 0.1;
  step = 0;
  pump();
  timer = setInterval(pump, TICK_MS);
}

export function stopMusic(): void {
  if (timer !== null) {
    clearInterval(timer);
    timer = null;
  }
  const ctx = getAudioContext();
  if (master && ctx) {
    // Ramp rather than disconnect: cutting a running oscillator chain produces a
    // click, which is a worse sound than the music was.
    try {
      master.gain.cancelScheduledValues(ctx.currentTime);
      master.gain.setValueAtTime(master.gain.value, ctx.currentTime);
      master.gain.linearRampToValueAtTime(0.0001, ctx.currentTime + 0.25);
    } catch {
      /* context gone; nothing to fade */
    }
    const dying = master;
    setTimeout(() => {
      try {
        dying.disconnect();
      } catch {
        /* already gone */
      }
    }, 400);
  }
  master = null;
}

export function musicRunning(): boolean {
  return timer !== null;
}
